name: tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      py38: "3.8"
      py39: "3.9"
      py310: "3.10"
      py311: "3.11"
      py312: "3.12"
    strategy:
      fail-fast: false
      matrix:
        python-version: [py38, py39, py310, py311, py312]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env[matrix.python-version] }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env[matrix.python-version] }}
        architecture: "x64"
    - run: pip install hatch
    - run: hatch run test
